# Generated by Django 3.2.15 on 2022-08-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='data',
            name='body',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
